### ISSUE TITLE
abide.json

### ISSUE THREAD

**Issue by sdalezman** [beme/abide#30]
Hey,

Love the library been really helpful in taking snapshot testing to our go libs. I've been trying to use abide.json defaults with code that looks like something like the following:

``` golang
type UserData struct {
	Name           string `json:"name"`
	Email          string `json:"email"`
}

func TestMyFn(t *testing.T) {
    randNum := rand.Intn(1000000000)
    // we generate random emails as user factories in our tests
    email := fmt.Sprintf("shlomo-%d@intello.io", randNum)

    u := []UserData{{"shlomo", email}}
    userBytes, err := json.Marshal(users)
    abide.AssertReader(t, tt.name, bytes.NewReader(userBytes))
}
```

my abide.json:

``` json
{
    "defaults": {
        "email": "foo"
    }
}

```

but it doesn't seem like abide picks up the defaults and in the snapshot the random email is stored and subsequent tests without an update fail. i define abide.json on the defaults of the lib. Happy to share a larger example if it's helpful.

Thanks!

**Comment by sjkaliski** [comment]
Hi @sdalezman, thanks for pointing this out! I just confirmed that the `abide.json` file is only considered when using `AssertHTTPResponse`, which is why you're running into this issue. That should be documented much better.

We've also come across this internally, especially around timestamps, uuid, etc. To maintain uniqueness without randomization, we've wrapped methods, such as [`time.Now().Unix()`](https://golang.org/pkg/time/#Time.Unix), so that in testing we can return an alternative value (incrementing integer) to the actual time. This enables our values to be unique and consistent between test runs. I don't know the full specifics of your case, but you could possibly increment an integer instead of using randomization.

In terms of an actionable, I'll make sure to update the README to clarify how the config file is used. In addition one improvement to `abide.json` we're considering is adding regex support. This would apply to all `Assert*` methods.

```json
{
  "defaults": {
    "foo": "bar"
  },
  "regex": {
    "[a-zA-Z0-9-_.]+@[a-zA-Z0-9-_.]+": "foo@bar.com"
  }
}
```

This would use [`regexp.ReplaceAllString`](https://golang.org/pkg/regexp/#Regexp.ReplaceAllString) method to find/replace all instances of that expression. However, this needs to be thought out a bit more (e.g. does `defaults` take precedence to `regex`).

Also, this may help.. there is a generic [`Assert`](https://godoc.org/github.com/beme/abide#Assert) method for types that implement `String() string`. For example

```go
func (ud *UserData) String() string {
  userBytes, _ := json.Marshal(&UserData{
    Name: ud.Name,
    Email: "foo@bar.com",
  })
  
  return string(userBytes)
}
```

--

I'd also love to learn more about how you're using the project at Intello! Feel drop me a line, steve@beme.com
